### ISSUE TITLE
Figure out delve

### ISSUE THREAD

**Issue by whit537** [whit537/consul#5]
Interactive debugger for go: https://github.com/derekparker/delve

**Comment by whit537** [comment]
Um ... I think installation worked?

![screen shot 2018-01-06 at 1 16 29 pm](https://user-images.githubusercontent.com/134455/34642608-d7e2a8d2-f2e3-11e7-8d6f-6f306d31bc96.png)

**Comment by whit537** [comment]
Nope! But https://github.com/go-delve/homebrew-delve/issues/19#issuecomment-330442033 worked around it. 👍

![screen shot 2018-01-06 at 1 25 25 pm](https://user-images.githubusercontent.com/134455/34642676-11c10174-f2e5-11e7-9336-f0a55f06cc19.png)

**Comment by whit537** [comment]
https://github.com/derekparker/delve/blob/master/Documentation/cli/getting_started.md#debugging-tests

**Comment by whit537** [comment]
💃 

https://github.com/derekparker/delve/blob/master/Documentation/cli/getting_started.md#debugging-tests

**Comment by whit537** [comment]
😍

![screen shot 2018-01-06 at 1 29 24 pm](https://user-images.githubusercontent.com/134455/34642705-a54d83d6-f2e5-11e7-978e-59c32bc6f84f.png)

**Comment by whit537** [comment]
Server floof might clobber stdio?

![screen shot 2018-01-06 at 1 30 07 pm](https://user-images.githubusercontent.com/134455/34642713-c09b0dc0-f2e5-11e7-9dc1-f18378bb4bf3.png)

**Comment by whit537** [comment]
Workaround lack of `-run`: https://github.com/derekparker/delve/issues/636.

Set breakpoint programmatically:

https://golang.org/pkg/runtime/#Breakpoint
https://stackoverflow.com/a/42357327

**Comment by whit537** [comment]
Now https://github.com/derekparker/delve/issues/769. What is the command line invocation?

**Comment by whit537** [comment]
I think the `--build-flags` is unnecessary. You can pass an import path directly to `dlv test`. It's the `-- -test.run FooBar` that does the trick of singly out a single test. However, that seems to clobber the `-N -i` needed to print symbols?

**Comment by whit537** [comment]
Alright, so I need a delve invocation that runs a single test _and_ provides debugging symbols.

**Comment by whit537** [comment]
Hmm ... don't seem to have debugging symbols whether or no I pass `-- -test.run FooBar`.

> Then you need to pass `-gcflags='-N -l'` to `go build`.

I think that applies since I'm doing `dlv test ./api` i.e., not testing main but "a package other than main."

https://github.com/derekparker/delve/issues/769

**Comment by whit537** [comment]
```
$ go build -gcflags='-N -l'
$ dlv test ./api
```

**Comment by whit537** [comment]
No go! 🤔

```
> github.com/hashicorp/consul/api.TestAPI_ClientPutGetDelete() ./api/kv_test.go:47 (PC: 0x15e36f2)
    42:         }
    43:
    44:         // Get should work
    45:         pair, meta, err := kv.Get(key, nil)
    46:         runtime.Breakpoint()
=>  47:         if err != nil {
    48:                 t.Fatalf("err: %v", err)
    49:         }
    50:         if pair == nil {
    51:                 t.Fatalf("expected value: %#v", pair)
    52:         }
(dlv) p err
Command failed: could not find symbol value for err
(dlv) p pair
Command failed: could not find symbol value for pair
(dlv) p meta
Command failed: could not find symbol value for meta
(dlv)
```

**Comment by whit537** [comment]
What if I `dlv test` w/ no package specified?

**Comment by whit537** [comment]
```
$ dlv test
Type 'help' for list of commands.
(dlv) c
testing: warning: no tests to run
PASS
Process 6612 has exited with status 0
(dlv)
```

**Comment by whit537** [comment]
> learn about packages

https://github.com/whit537/consul/issues/1#issuecomment-355650217
https://golang.org/cmd/go/#hdr-Description_of_package_lists
https://www.golang-book.com/books/intro/11

**Comment by whit537** [comment]
```
go list -f '{{.Name|printf "%16s"}} {{.ImportPath|printf "%-64s"}} {{.Target}}' all | less
```

https://golang.org/pkg/text/template/

**Comment by whit537** [comment]
https://github.com/derekparker/delve/blob/master/Documentation/usage/dlv_test.md

**Comment by whit537** [comment]
```
$ go test
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/consul     0.060s
$
```

So that's consistent. I saw something somewhere about `main` being special-cased? Because I do find a `main_test.go` file. Hmm ... 🤔

Oh. 😊

https://github.com/whit537/consul/blob/8837a18d25fc2555150db761f1d922a3fc2ffae3/main_test.go

**Comment by whit537** [comment]
💃

```
$ go test
PASS
ok      github.com/hashicorp/consul     0.076s
$
```

```diff
diff --git a/main_test.go b/main_test.go
index 06ab7d0..57cec56 100644
--- a/main_test.go
+++ b/main_test.go
@@ -1 +1,6 @@
 package main
+
+import "testing"
+
+func TestSomthing(t *testing.T) {
+}
```

**Comment by whit537** [comment]
```
$ go test
SIGTRAP: trace trap
PC=0x40584e1 m=0 sigcode=1

goroutine 6 [running]:
runtime.breakpoint()
	/Users/whit537/personal/golang/go/src/runtime/asm_amd64.s:273 +0x1 fp=0xc420057f88 sp=0xc420057f80 pc=0x40584e1
runtime.Breakpoint()
	/Users/whit537/personal/golang/go/src/runtime/proc.go:3440 +0x20 fp=0xc420057f98 sp=0xc420057f88 pc=0x4036e10
github.com/hashicorp/consul.TestSomthing(0xc4202ec1e0)
	/Users/whit537/go/src/github.com/hashicorp/consul/main_test.go:9 +0x20 fp=0xc420057fa8 sp=0xc420057f98 pc=0x4aedcc0
testing.tRunner(0xc4202ec1e0, 0x4f7a928)
	/Users/whit537/personal/golang/go/src/testing/testing.go:769 +0xc0 fp=0xc420057fd0 sp=0xc420057fa8 pc=0x40f0c30
runtime.goexit()
	/Users/whit537/personal/golang/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420057fd8 sp=0xc420057fd0 pc=0x405b161
created by testing.(*T).Run
	/Users/whit537/personal/golang/go/src/testing/testing.go:812 +0x2a5

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4202ec1e0, 0x4f2df7d, 0xc, 0x4f7a928, 0x407cc66)
	/Users/whit537/personal/golang/go/src/testing/testing.go:813 +0x2c6
testing.runTests.func1(0xc4202ec0f0)
	/Users/whit537/personal/golang/go/src/testing/testing.go:1036 +0x64
testing.tRunner(0xc4202ec0f0, 0xc420259df8)
	/Users/whit537/personal/golang/go/src/testing/testing.go:769 +0xc0
testing.runTests(0xc4202e7320, 0x58ea430, 0x1, 0x1, 0x4012b09)
	/Users/whit537/personal/golang/go/src/testing/testing.go:1034 +0x296
testing.(*M).Run(0xc4202f15e0, 0x0)
	/Users/whit537/personal/golang/go/src/testing/testing.go:954 +0x15c
main.main()
	b001/_testmain.go:42 +0x151

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/Users/whit537/personal/golang/go/src/runtime/sigqueue.go:131 +0xa7
os/signal.loop()
	/Users/whit537/personal/golang/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/Users/whit537/personal/golang/go/src/os/signal/signal_unix.go:28 +0x41

rax    0x4aedca0
rbx    0x0
rcx    0xc420001800
rdx    0x4f7a928
rdi    0xc4202ec280
rsi    0x3e8e08e1cefadff2
rbp    0xc420057f88
rsp    0xc420057f80
r8     0x5a57ac07
r9     0x3ac55e8b15728f7c
r10    0x44b899df8
r11    0x3b9aca00
r12    0xb778ebdf600
r13    0xff
r14    0xff
r15    0xf
rip    0x40584e1
rflags 0x216
cs     0x2b
fs     0x0
gs     0x0
exit status 2
FAIL	github.com/hashicorp/consul	0.102s

```

```diff
diff --git a/main_test.go b/main_test.go
index 06ab7d0..dc4f4a4 100644
--- a/main_test.go
+++ b/main_test.go
@@ -1 +1,10 @@
 package main
+
+import (
+	"runtime"
+	"testing"
+)
+
+func TestSomthing(t *testing.T) {
+	runtime.Breakpoint()
+}
```

**Comment by whit537** [comment]
🤔

```
$ dlv test
Type 'help' for list of commands.
(dlv) c
> github.com/hashicorp/consul.TestSomthing() ./main_test.go:10 (PC: 0x4f952e0)
     5:         "testing"
     6: )
     7:
     8: func TestSomthing(t *testing.T) {
     9:         runtime.Breakpoint()
=>  10: }
(dlv) print runtime
Command failed: could not find symbol value for runtime
(dlv) print testing
Command failed: could not find symbol value for testing
(dlv) foo := "bar"
Command failed: command not available
(dlv)
```

**Comment by whit537** [comment]
```
$ dlv test
# github.com/hashicorp/consul
./main_test.go:9:2: foo declared and not used
$
```

```diff
diff --git a/main_test.go b/main_test.go
index 06ab7d0..04600b8 100644
--- a/main_test.go
+++ b/main_test.go
@@ -1 +1,11 @@
 package main
+
+import (
+	"runtime"
+	"testing"
+)
+
+func TestSomthing(t *testing.T) {
+	foo := "bar"
+	runtime.Breakpoint()
+}
```

**Comment by whit537** [comment]
🤔

```
$ dlv test
Type 'help' for list of commands.
(dlv) c
> github.com/hashicorp/consul.TestSomthing() ./main_test.go:11 (PC: 0x4f95297)
     6: )
     7:
     8: func TestSomthing(t *testing.T) {
     9:         foo := "bar"
    10:         runtime.Breakpoint()
=>  11:         println(foo)
    12: }
(dlv) print foo
Command failed: could not find symbol value for foo
(dlv)
```

**Comment by whit537** [comment]
ftr

```
(dlv) c
bar
PASS
Process 6853 has exited with status 0
(dlv)
```

**Comment by whit537** [comment]
> Compiles a test binary with optimizations disabled and begins a new debug session.
>
> The test command allows you to begin a new debug session in the context of your unit tests. By default Delve will debug the tests in the current directory. Alternatively you can specify a package name, and Delve will debug the tests in that package instead.

https://github.com/derekparker/delve/blob/master/Documentation/usage/dlv_test.md

**Comment by whit537** [comment]
Switched away from the `go` version I compiled while working on https://github.com/golang/go/issues/22326. Now I just have the stock brew version:

```
$ which -a go
/usr/local/bin/go
$ go version
go version go1.9.2 darwin/amd64
$
```

**Comment by whit537** [comment]
💃

```
$ dlv test
Type 'help' for list of commands.
(dlv) c
> github.com/hashicorp/consul.TestSomthing() ./main_test.go:11 (PC: 0x5056ef7)
     6: )
     7:
     8: func TestSomthing(t *testing.T) {
     9:         foo := "bar"
    10:         runtime.Breakpoint()
=>  11:         println(foo)
    12: }
(dlv) p foo
"bar"
(dlv)
```

**Comment by whit537** [comment]
😍 💃 

```
(dlv) list
> github.com/hashicorp/consul/api.TestAPI_ClientPutGetDelete() ./api/kv_test.go:47 (PC: 0x1614b6d)
    42:         }
    43:
    44:         // Get should work
    45:         pair, meta, err := kv.Get(key, nil)
    46:         runtime.Breakpoint()
=>  47:         if err != nil {
    48:                 t.Fatalf("err: %v", err)
    49:         }
    50:         if pair == nil {
    51:                 t.Fatalf("expected value: %#v", pair)
    52:         }
(dlv) p err
error nil
(dlv) p meta
*github.com/hashicorp/consul/api.QueryMeta {LastIndex: 7, LastContact: 0, KnownLeader: true, RequestTime: 520274, AddressTranslationEnabled: false}
(dlv) p pair
*github.com/hashicorp/consul/api.KVPair {
        Key: "2193514b-8718-d2f2-1767-89e9fae1ebd8",
        CreateIndex: 7,
        ModifyIndex: 7,
        LockIndex: 0,
        Flags: 42,
        Value: []uint8 len: 4, cap: 6, [116,101,115,116],
        Session: "",}
(dlv)
```

**Comment by whit537** [comment]
That's with `dlv test ./api`.

With that, I'm considering this closed!

**Comment by whit537** [comment]
P.S. https://github.com/derekparker/delve/pull/1080 ☺️

**Comment by whit537** [comment]
Oh! Single test run?

**Comment by whit537** [comment]
```
$ dlv test ./api -- -test.run Authori
Type 'help' for list of commands.
(dlv) c
> github.com/hashicorp/consul/api.TestAPI_ClientAuthorization() ./api/kv_test.go:579 (PC: 0x161e890)
   574:         }
   575: }
   576:
   577: func TestAPI_ClientAuthorization(t *testing.T) {
   578:         runtime.Breakpoint()
=> 579: }
(dlv)
```

**Comment by whit537** [comment]
💃
